### ISSUE TITLE
The word University in the licenses episode should be lower case.

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/DCC-Rpackaging-lesson#13]
Correct University to university in the Licenses episode, file [episodes/licenses.Rmd](https://github.com/esciencecenter-digital-skills/DCC-Rpackaging-lesson/blob/main/episodes/licenses.Rmd) on [line 32](https://github.com/esciencecenter-digital-skills/DCC-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/licenses.Rmd#L32C41-L32C51).

See the [Licenses episode](https://esciencecenter-digital-skills.github.io/DCC-Rpackaging-lesson/licenses.html) of the lesson.

**Comment by stzv** [comment]
For some reason did not close automatically, closing manual.
