### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/DCC-Rpackaging-lesson#6]
In the [README.md file](https://github.com/esciencecenter-digital-skills/DCC-Rpackaging-lesson/blob/main/README.md), there is an italic sentence that states we need a sentence that describes what the lesson is about. We should add this so that people who visit the repository can understand what they are looking at.

**Comment by FenneRiemslagh** [comment]
Yes you're right we should this information!
